version: "3.9"

services:
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  app:
    container_name: users_redis
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app
    links:
      - redis
    depends_on:
      - redis 

